{
  'include_dirs': [
    '..',
  ],
  'sources': [
    'runtime/browser/application_component.cc',
    'runtime/browser/application_component.h',
    'runtime/browser/xwalk_browser_context.cc',
    'runtime/browser/xwalk_browser_context.h',
    'runtime/browser/runtime_download_manager_delegate.cc',
    'runtime/browser/runtime_download_manager_delegate.h',
    'runtime/browser/runtime_network_delegate.cc',
    'runtime/browser/runtime_network_delegate.h',
    'runtime/browser/runtime_url_request_context_getter.cc',
    'runtime/browser/runtime_url_request_context_getter.h',
    'runtime/browser/storage_component.cc',
    'runtime/browser/storage_component.h',
    'runtime/browser/sysapps_component.cc',
    'runtime/browser/sysapps_component.h',
    'runtime/browser/ui/native_app_window.cc',
    'runtime/browser/ui/native_app_window.h',
    'runtime/common/xwalk_common_messages.cc',
    'runtime/common/xwalk_common_messages.h',
    'runtime/common/xwalk_common_message_generator.cc',
    'runtime/common/xwalk_common_message_generator.h',
    'runtime/common/xwalk_runtime_features.h',
    'runtime/common/xwalk_runtime_features.cc',
    'runtime/common/xwalk_switches.h"',
    'runtime/common/xwalk_switches.cc',
    'runtime/common/xwalk_system_locale.cc',
    'runtime/common/xwalk_system_locale.h',
  ],
  'includes': [
    'xwalk_jsapi.gypi',
  ],
}
